#!/bin/bash

#Check folder backup is exsisting
if [ ! -d /opt/backup ]; then
    echo "Create Backup Folder"
    mkdir /opt/backup
    if [ ! -d /opt/backup/database ]; then
        mkdir /opt/backup/database
    fi
fi

if [ $1 == add ]; then
    #Variable Database
    echo "Create new database $2"
    echo "Create user database $3"
    echo "Create password for user database $4"

    # Check config in /root/.my.cnf
    if [ -f /root/.my.cnf ]; then
        echo "Database config found"
            mysql -e "CREATE DATABASE $2;"
            mysql -e "show databases;"
            mysql -e "CREATE USER $3@localhost IDENTIFIED BY '$4';"
        echo "Database user $3 successfully created"
        echo "Giving privilege $3 to Database $2!"
            mysql -e "GRANT ALL PRIVILEGES ON $2.* TO '$3'@'localhost';"
            mysql -e "FLUSH PRIVILEGES;"
        echo "Database is ready to use!"
    else
    # If /root/.my.cnf nothing
        echo "Database config not found"
        echo "Input your database root password: "
        read -s rootpasswd
            mysql -uroot -p${rootpasswd} -e "CREATE DATABASE $2;"
	        mysql -uroot -p${rootpasswd} -e "show databases;"
            mysql -uroot -p${rootpasswd} -e "CREATE USER $3@localhost IDENTIFIED BY '$4';"
        echo "Database user $3 successfully created"
	    echo "Giving privilege $3 to Database $2!"
            mysql -uroot -p${rootpasswd} -e "GRANT ALL PRIVILEGES ON $2.* TO '$3'@'localhost';"
            mysql -uroot -p${rootpasswd} -e "FLUSH PRIVILEGES;"
        echo "Database is ready to use!"
    fi

elif [ $1 == backup ]; then
    # Check config in /root/.my.cnf
    if [ -f /root/.my.cnf ]; then
	echo "Database config found"
	    mysql -e "show databases;"
    echo "Perform database backup process $2"
        namafiledb=$2-$(date +%y%m%d).sql
        mysqldump -e $2 > /opt/backup/database/$namafiledb
    else
    # If /root/.my.cnf nothing
        echo "Database config not found"
        echo "Input your database root password: "
        read -s rootpasswd
            mysql -u root -p${rootpasswd} -e "show databases;"
        echo "Perform database backup process $2"
            namafiledb=$2-$(date +%y%m%d).sql
            mysqldump -u root -p $2 > /opt/backup/database/$namafiledb
    fi

else
    echo "Keyword not found"
fi

elif [ $1 == restore ]; then
    echo "Restoring database $2 with file $3"
    # Check config in /root/.my.cnf
    if [ -f /root/.my.cnf ]; then
	echo "Database config found"
	mysql -e "create database $2;"
        if [ $? -eq 0 ]; then
            echo "Database successfully created"
            mysql -u root $2 < $3
            if [ $? -eq 0 ]; then
                echo "Database was restored"
            else
                echo "Database was not successfully created"
            fi
        else
            echo "Database already exists"
            echo "Are you sure want to restoration database $2? [y/n]: "
            read -e dbokay
            if [ "$dbokay" == y ] || [ "$dbokay" == Y ]; then
                mysql -u root $2 < $3
                if [ $? -eq 0 ]; then
                    echo "Database was restored"
                else
                    echo "Database was not successfully created"
                fi
            else
                exit
            fi
        fi
    else
    # If /root/.my.cnf nothing
        echo "Database config not found"
        echo "Input your database root password: "
        read -s rootpasswd
        mysql -u root -p${rootpasswd} -e "create database $2;"
        if [ $? -eq 0 ]; then
            echo "Database successfully created"
            mysql -u root -p${rootpasswd} $2 < $3
            if [ $? -eq 0 ]; then
                echo "Database was restored"
            else
                echo "Database was not successfully created"
            fi
        else
            echo "Database already exists"
            echo "Are you sure want to restoration database $2? [y/n]: "
            read -e dbokay
            if [ "$dbokay" == y ] || [ "$dbokay" == Y ]; then
                mysql -u root -p${rootpasswd} $2 < $3
                if [ $? -eq 0 ]; then
                    echo "Database was restored"
                else
                    echo "Database was not successfully created"
                fi
            else
                exit
            fi
        fi

else
    echo "Keyword not found"
fi