#!/bin/bash

#Check folder backup is exsisting
if [ ! -d /opt/backup ]; then
    echo "Create Backup Folder"
    mkdir /opt/backup
    if [ ! -d /opt/backup/database ]; then
        mkdir /opt/backup/database
    fi
fi

if [ $1 == tambah ]; then
    #Variable Database
    echo "Create new database $2"
    echo "Create user database $3"
    echo "Create password for user database $4"

    # Check config in /root/.my.cnf
    if [ -f /root/.my.cnf ]; then
        echo "Database config found"
            mysql -e "CREATE DATABASE $2;"
            mysql -e "show databases;"
            mysql -e "CREATE USER $3@localhost IDENTIFIED BY '$4';"
        echo "Database user $3 successfully created"
        echo "Giving privilege $3 to Database $2!"
            mysql -e "GRANT ALL PRIVILEGES ON $2.* TO '$3'@'localhost';"
            mysql -e "FLUSH PRIVILEGES;"
        echo "Database is ready to use!"
    else
    # If /root/.my.cnf nothing
        echo "Database config not found"
        echo "Input your database root password: "
        read -s rootpasswd
            mysql -uroot -p${rootpasswd} -e "CREATE DATABASE $2;"
	        mysql -uroot -p${rootpasswd} -e "show databases;"
            mysql -uroot -p${rootpasswd} -e "CREATE USER $3@localhost IDENTIFIED BY '$4';"
        echo "Database user $3 successfully created"
	    echo "Giving privilege $3 to Database $2!"
            mysql -uroot -p${rootpasswd} -e "GRANT ALL PRIVILEGES ON $2.* TO '$3'@'localhost';"
            mysql -uroot -p${rootpasswd} -e "FLUSH PRIVILEGES;"
        echo "Database is ready to use!"
    fi

elif [ $1 == backup ]; then
    # Periksa Pass DB root in /root/.my.cnf ada
    if [ -f /root/.my.cnf ]; then
	echo "Database config found"
	    mysql -e "show databases;"
    echo "Perform database backup process $2"
        namafiledb=$2-$(date +%y%m%d).sql
        mysqldump -e $2 > /opt/backup/database/$namafiledb
    else
    # Jika /root/.my.cnf tidak ada
        echo "Database config not found"
        echo "Input your database root password: "
        read -s rootpasswd
            mysql -u root -p${rootpasswd} -e "show databases;"
        echo "Perform database backup process $2"
            namafiledb=$2-$(date +%y%m%d).sql
            mysqldump -u root -p $2 > /opt/backup/database/$namafiledb
    fi

else
    echo "Keyword not found"
fi